name: rcldart
version: 0.2.2
author: Tim Whiting
description: A Dart interface to the ROS 2 Client Library through Dart FFI.
homepage: https://github.com/TimWhiting/rcldart.git
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  ffi: any
dev_dependencies:
  ffigen: any

dependency_overrides:
  ffigen:
    git: https://github.com/dart-lang/ffigen

ffigen:
  output: "src/generated_bindings.dart"
  headers:
    entry-points:
      - "rcl/rcl.h"
    include-directives:
      - "rcl/**"
  name: "RCL"
  description: "Bindings to the ros client library dynamic libraries"
  array-workaround: true
  comments:
    style: any
