name: rcldart
version: 0.2.2
author: Tim Whiting
description: A Dart interface to the ROS 2 Client Library through Dart FFI.
homepage: https://github.com/TimWhiting/rcldart.git
environment:
  sdk: ">=2.13.0-0 <3.0.0"
dependencies:
  dartx: any
  ffi: any
dev_dependencies:
  ffigen: 3.0.0-beta.0
  test: ^1.17.3

ffigen:
  output: "lib/src/gen/ffi_bindings.dart"
  headers:
    entry-points:
      - "/opt/ros/eloquent/include/rcl/*.h"
    include-directives:
      - "/opt/ros/eloquent/include/**/*"
  compiler-opts: "-I/usr/lib/llvm-9/include/ -I/opt/ros/eloquent/include/"
  name: "RCL"
  comments:
    style: any
  description: "Bindings to the ros client library dynamic libraries\n"
