name: rcldart
version: 0.2.2
author: Tim Whiting
description: A Dart interface to the ROS 2 Client Library through Dart FFI.
homepage: https://github.com/TimWhiting/rcldart.git
environment:
  sdk: ">=2.12.0-198.0 <3.0.0"
dependencies:
  ffi: any
dev_dependencies:
  ffigen: 2.0.0-dev.2

ffigen:
  output: "lib/src/generated_bindings.dart"
  headers:
    entry-points:
      - "/opt/ros/foxy/include/rcl/rcl.h"
    include-directives:
      - "/opt/ros/foxy/include/**/*"
  compiler-opts: "-I/usr/lib/llvm-9/include/ -I/opt/ros/foxy/include/"
  name: "RCL"
  description: "Bindings to the ros client library dynamic libraries"
  array-workaround: true
